services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: conan-frontend-dev
    ports:
      - "3003:3000"
    volumes:
      # Mount source code for hot reload
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - app-network
    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  app-network:
    driver: bridge
